Fixed crashes on parsing and serialization
xackus/zig-lsp pull request #1
Opened 2020-05-06 11:18 UTC by Sergeeeek

2020-05-06 21:12 UTC, xackus requested changes
Thanks for the PR!

You are right about the hack. I have already submitted a PR to upstream.

I think the warns will be too verbose.
Please remove them (except for the one that prints on errors).
If you are using vscode you can turn on logging. https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#logging-support-for-language-server

2020-05-06 21:12 UTC, xackus commented on src/protocol.zig
>          if (line.len <= 1) { // \r
```suggestion
        if (line.len == 0) {
```

2020-05-06 21:12 UTC, xackus commented on src/protocol.zig
>      }
instead of writing a loop, use `readAll`

2020-05-07 04:58 UTC, Sergeeeek commented
Thanks for the feedback, fixed all of your comments

2020-05-07 17:43 UTC, merged